# Generated by Django 4.2.15 on 2024-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
