# Generated by Django 4.2.15 on 2024-08-23 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obra', '0003_alter_obra_precio'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.obra')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.perfil')),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_like', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.perfil')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicacion.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.perfil')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicacion.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
