# Generated by Django 4.2.15 on 2024-08-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obra', '0003_alter_obra_precio'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.perfil')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.obra')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
