# Generated by Django 4.2.15 on 2024-08-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripción', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estilos',
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=False)),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.estilo')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.tecnica')),
            ],
            options={
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(max_length=255, upload_to='imgs/fotos/')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.obra')),
            ],
            options={
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
