# Generated by Django 4.2.15 on 2024-08-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_rename_descripción_estilo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
