@base_url = http://localhost:8001/api/

### Login
POST {{base_url}}auth/login/ HTTP/1.1
content-type: application/json

{
    "username": "aneachi",
    "password": "1234"
}


### getUsuarios
GET {{base_url}}auth/usuarios/ HTTP/1.1
content-type: application/json
withCredentials: true


### register
POST {{base_url}}auth/usuarios/ HTTP/1.1
Content-Type: application/json
withCredentials: true

{
    "username": "nuevo_usuario",
    "password": "password_seguro",
    "first_name": "Nombre",
    "last_name": "Apellido",
    "email": "email@example.com"
}


### getPerfiles
GET {{base_url}}auth/perfiles/ HTTP/1.1
content-type: application/json
withCredentials: true


### getPerfilesById
GET {{base_url}}auth/perfiles/1/ HTTP/1.1
content-type: application/json
withCredentials: true


### postPerfil
POST {{base_url}}auth/perfiles/ HTTP/1.1
content-type: application/json
withCredentials: true

{
    "user": 1
}


### updatePerfiles
PATCH {{base_url}}auth/perfiles/1/ HTTP/1.1
content-type: application/json
withCredentials: true

{
    "biografia": "me gustan las patatas"
}


### deletePerfil
DELETE {{base_url}}auth/perfiles/0/ HTTP/1.1
content-type: application/json
withCredentials: true