# Generated by Django 4.2.15 on 2024-08-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bigrafia',
            new_name='biografia',
        ),
    ]
